name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: pylogx

    - name: install pylogx
      run: python3 -m pip install pylogx

    - name: run pytests
      run: |
        cd pylogx
        pytest tests/*
