name: CI

on:
  push:
    branches: [ main, releases/** ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: pylogx

    - name: install pylogx
      run: |
        pip3 install pytest
        python3 -m pip install pylogx/

    - name: run pytests
      run: |
        cd pylogx
        pytest tests/*
