name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: releases/**

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: pylogx

    - name: build pylogx
      run: |
        echo building pylogx

    - name: publish pylogx
      run: |
        echo publishing pylogx
