name: release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: releases/**

jobs:
  publish-pylox:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install build
        echo building pylogx

    - name: build pylogx
      run: python3 -m build

    - name: publish pylogx
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
